import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Render content based on authentication state */}
          <SignedOut>
            {/* You can render signed-out specific content here */}
            {children}
          </SignedOut>

          <SignedIn>
            {/* Render signed-in specific content */}
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
